# Pipeline Azure DevOps - Exemple structuré
# Documentation : https://aka.ms/yaml

trigger:
  branches:
    include:
      - main     # Change ici en 'master' si ta branche s'appelle master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# 1️⃣ Vérifier le code (checkout)
- checkout: self
  displayName: "Récupération du code source"

# 2️⃣ Installer dépendances (exemple Node.js)
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: "Installer Node.js"

- script: |
    npm install
  displayName: "Installer les dépendances"

# 3️⃣ Build
- script: |
    npm run build
  displayName: "Construire l'application"

# 4️⃣ Tests
- script: |
    npm test
  displayName: "Exécuter les tests"

# 5️⃣ Publier les artefacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/dist'
    ArtifactName: 'drop'
  displayName: "Publier les artefacts de build"
